include:
  - ./docker-compose-dev.yml

services:
  backend:
      build: .
      container_name: shopping_backend
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopping
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=6379
        - UPLOAD_PATH=uploads
      env_file:
        - .env
      volumes:
        - ./uploads:/app/uploads
      depends_on:
        - postgres
        - redis