include:
  - ./docker-compose-dev.yml

services:
  backend:
      build: .
      container_name: shopping_backend
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopping
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=6379
        - SPRING_RABBITMQ_HOST=rabbitmq
        - UPLOAD_PATH=uploads
        - SPRING_JPA_SHOW-SQL=false
      env_file:
        - .env
      volumes:
        - ./uploads:/app/uploads
      depends_on:
        - postgres
        - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - BACKEND_URL=http://backend:8080/api/v1
    env_file:
      - frontend/.env.local
    depends_on:
      - backend