server:
  port: 8080
app:
  url: http://localhost:${server.port}
  db:
    init:
      product-count: 1000
      user-count: 100
frontend:
  url: http://localhost:3000
  password-reset-url: ${frontend.url}/account/reset-password
  account-url: ${frontend.url}/account
logging:
  level:
#    root: DEBUG
    web: INFO
    com:
      dotcom:
        retail: DEBUG
spring:
  application:
    name: dot-com-retail
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        function_contributor: com.dotcom.retail.config.db.FunctionContributor
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${app.url}/api/v1/oauth2/code/{registrationId}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            redirect-uri: ${app.url}/api/v1/oauth2/code/{registrationId}
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}
  access:
    exp: 900000 # 15 minutes
  refresh:
    exp: 345600000 # 4 days

password:
  reset:
    duration: 15m
file:
  root: ${UPLOAD_PATH}
  structure:
    images: images
    products: product
    brands: brand

cloudflare:
  turnstile:
    secret-key: ${TURNSTILE_SECRET_KEY}
    verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify

stripe:
  apiKey: ${STRIPE_API_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}


ratelimit:
  capacity: 100
  refill: 100
  refill-interval: 1m
  bucket-expiration: 2m