
server.port=8080
app.url=http://localhost:${server.port}

frontend.url=http://localhost:3000

#logging.level.root=DEBUG
logging.level.web=INFO
logging.level.com.dotcom.retail=DEBUG

spring.application.name=dot-com-retail
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 15 minutes
jwt.access.exp.ms=900000
# 4 days
jwt.refresh.exp.ms=345600000

jwt.secret=VGfucERcmymq3JmsYjDczP5Ntb2O3DM3BjtAg6ouk8p

spring.security.oauth2.client.registration.google.redirect-uri=${app.url}/api/v1/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.redirect-uri=${app.url}/api/v1/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email